# Generated by Django 5.2 on 2025-05-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_address_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='discription',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='offers',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
