# Generated by Django 5.2.1 on 2025-05-19 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_gallery_rating_gallery_vector_data_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.gallery')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.users')),
            ],
        ),
    ]
